# Cars24 is one of the leading used-car buying and selling platform in India.

### **1.1 Imports**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### **1.2 Load Dataset**

In [6]:
df = pd.read_csv("./data/cars24-car-price.csv")
df

,full_name,selling_price,year,seller_type,km_driven,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Maruti Alto Std,1.20,2012.0,Individual,120000,Petrol,Manual,19.70,796.0,46.30,5.0
1,Hyundai Grand i10 Asta,5.50,2016.0,Individual,20000,Petrol,Manual,18.90,1197.0,82.00,5.0
2,Hyundai i20 Asta,2.15,2010.0,Individual,60000,Petrol,Manual,17.00,1197.0,80.00,5.0
3,Maruti Alto K10 2010-2014 VXI,2.26,2012.0,Individual,37000,Petrol,Manual,20.92,998.0,67.10,5.0
4,Ford Ecosport 2015-2021 1.5 TDCi Titanium BSIV,5.70,2015.0,Dealer,30000,Diesel,Manual,22.77,1498.0,98.59,5.0
...,...,...,...,...,...,...,...,...,...,...,...
19975,Toyota Platinum Etios 1.4 GXD,6.50,2017.0,Dealer,69480,Diesel,Manual,23.59,1364.0,67.05,5.0
19976,Maruti Ertiga BSIV VXI,9.25,2019.0,Dealer,18000,Petrol,Manual,17.50,1373.0,91.10,7.0
19977,Skoda Rapid 1.5 TDI Elegance,4.25,2015.0,Dealer,67000,Diesel,Manual,21.14,1498.0,103.52,5.0
19978,Mahindra XUV500 W6 2WD,12.25,2016.0,Dealer,3800000,Diesel,Manual,16.00,2179.0,140.00,7.0
19979,Honda City i-VTEC CVT VX,12.00,2019.0,Dealer,13000,Petrol,Automatic,18.00,1497.0,117.60,5.0